"""
HTML report generation for tap tone analysis.
"""

import base64
import io
from typing import Dict, Any, List, Optional
from datetime import datetime
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.figure import Figure


def generate_html_report(
    session_meta: Dict[str, Any],
    spectrum_data: Dict[str, Any],
    peaks: List[Dict[str, float]],
    wood_properties: Optional[Dict[str, Any]] = None,
    coherence_stats: Optional[Dict[str, Any]] = None,
    output_path: Optional[str] = None
) -> str:
    """
    Generate an HTML report for tap tone analysis.

    Args:
        session_meta: Session metadata
        spectrum_data: Spectrum data (freq_hz, H_mag, coherence, phase_deg)
        peaks: List of detected peaks
        wood_properties: Estimated wood properties
        coherence_stats: Coherence quality statistics
        output_path: Optional path to save the report

    Returns:
        HTML string
    """
    # Generate charts as base64-encoded images
    spectrum_chart = _generate_spectrum_chart_base64(spectrum_data)
    coherence_chart = _generate_coherence_chart_base64(spectrum_data)

    # Build HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tap Tone Analysis Report - {session_meta.get('specimen_id', 'Unknown')}</title>
    <style>
        {_get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🎸 Tap Tone Analysis Report</h1>
            <p class="subtitle">Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        </header>

        <section class="specimen-info">
            <h2>Specimen Information</h2>
            {_render_specimen_info(session_meta)}
        </section>

        <section class="spectrum">
            <h2>Transfer Function</h2>
            <div class="chart-container">
                <img src="data:image/png;base64,{spectrum_chart}" alt="Spectrum Chart">
            </div>
        </section>

        <section class="coherence">
            <h2>Coherence Analysis</h2>
            <div class="chart-container">
                <img src="data:image/png;base64,{coherence_chart}" alt="Coherence Chart">
            </div>
            {_render_coherence_stats(coherence_stats)}
        </section>

        <section class="peaks">
            <h2>Detected Resonance Peaks</h2>
            {_render_peaks_table(peaks)}
        </section>

        {_render_wood_properties(wood_properties) if wood_properties else ''}

        <footer>
            <p>Report generated by Tap Tone Analyzer v0.1.0</p>
            <p>Part of the tap_tone_pi project</p>
        </footer>
    </div>
</body>
</html>
"""

    if output_path:
        Path(output_path).write_text(html, encoding='utf-8')

    return html


def _get_css_styles() -> str:
    """Return CSS styles for the report."""
    return """
        :root {
            --bg-primary: #1e1e1e;
            --bg-secondary: #252526;
            --bg-tertiary: #2d2d2d;
            --text-primary: #cccccc;
            --text-secondary: #9d9d9d;
            --accent: #007acc;
            --accent-light: #1177bb;
            --success: #4ec9b0;
            --warning: #ce9178;
            --error: #f14c4c;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background-color: var(--bg-primary);
            color: var(--text-primary);
            line-height: 1.6;
        }

        .container {
            max-width: 1000px;
            margin: 0 auto;
            padding: 2rem;
        }

        header {
            text-align: center;
            margin-bottom: 2rem;
            padding-bottom: 1rem;
            border-bottom: 2px solid var(--accent);
        }

        header h1 {
            font-size: 2rem;
            color: var(--text-primary);
        }

        .subtitle {
            color: var(--text-secondary);
            margin-top: 0.5rem;
        }

        section {
            background-color: var(--bg-secondary);
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
        }

        h2 {
            color: var(--accent);
            font-size: 1.3rem;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 1px solid var(--bg-tertiary);
        }

        .info-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 1rem;
        }

        .info-item {
            background-color: var(--bg-tertiary);
            padding: 0.75rem;
            border-radius: 4px;
        }

        .info-item label {
            display: block;
            color: var(--text-secondary);
            font-size: 0.8rem;
            margin-bottom: 0.25rem;
        }

        .info-item span {
            font-size: 1.1rem;
            font-weight: 500;
        }

        .chart-container {
            background-color: var(--bg-tertiary);
            border-radius: 4px;
            padding: 1rem;
            text-align: center;
        }

        .chart-container img {
            max-width: 100%;
            height: auto;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 1rem;
        }

        th, td {
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid var(--bg-tertiary);
        }

        th {
            background-color: var(--bg-tertiary);
            color: var(--accent);
            font-weight: 500;
        }

        tr:hover {
            background-color: var(--bg-tertiary);
        }

        .grade {
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 4px;
            font-weight: bold;
        }

        .grade-aaa, .grade-aa, .grade-a {
            background-color: var(--success);
            color: var(--bg-primary);
        }

        .grade-b {
            background-color: var(--accent);
            color: white;
        }

        .grade-c {
            background-color: var(--warning);
            color: var(--bg-primary);
        }

        .grade-d {
            background-color: var(--error);
            color: white;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 1rem;
            margin-top: 1rem;
        }

        .stat-card {
            background-color: var(--bg-tertiary);
            padding: 1rem;
            border-radius: 4px;
            text-align: center;
        }

        .stat-card .value {
            font-size: 1.5rem;
            font-weight: bold;
            color: var(--accent);
        }

        .stat-card .label {
            color: var(--text-secondary);
            font-size: 0.8rem;
        }

        footer {
            text-align: center;
            padding-top: 2rem;
            color: var(--text-secondary);
            font-size: 0.9rem;
        }

        @media print {
            body {
                background-color: white;
                color: black;
            }
            .container {
                max-width: 100%;
            }
            section {
                break-inside: avoid;
            }
        }
    """


def _render_specimen_info(meta: Dict[str, Any]) -> str:
    """Render specimen information section."""
    dimensions = meta.get("dimensions_mm", {})

    items = [
        ("Specimen ID", meta.get("specimen_id", "Unknown")),
        ("Species", meta.get("species", "Unknown")),
        ("Grade", meta.get("grade", "-")),
        ("Length", f"{dimensions.get('length', '-')} mm"),
        ("Width", f"{dimensions.get('width', '-')} mm"),
        ("Thickness", f"{dimensions.get('thickness', '-')} mm"),
        ("Weight", f"{meta.get('weight_g', '-')} g"),
        ("Moisture", f"{meta.get('moisture_content_pct', '-')}%"),
    ]

    html = '<div class="info-grid">'
    for label, value in items:
        html += f"""
            <div class="info-item">
                <label>{label}</label>
                <span>{value}</span>
            </div>
        """
    html += '</div>'

    return html


def _render_coherence_stats(stats: Optional[Dict[str, Any]]) -> str:
    """Render coherence statistics."""
    if not stats:
        return ""

    grade = stats.get("quality_grade", "?")
    grade_class = f"grade-{grade.lower()}"

    return f"""
        <div class="stats-grid">
            <div class="stat-card">
                <div class="value">{stats.get('mean', 0):.3f}</div>
                <div class="label">Mean Coherence</div>
            </div>
            <div class="stat-card">
                <div class="value">{stats.get('min', 0):.3f}</div>
                <div class="label">Min Coherence</div>
            </div>
            <div class="stat-card">
                <div class="value">{stats.get('pct_above_threshold', 0):.1f}%</div>
                <div class="label">Above 0.9</div>
            </div>
            <div class="stat-card">
                <div class="value"><span class="grade {grade_class}">{grade}</span></div>
                <div class="label">Quality Grade</div>
            </div>
        </div>
    """


def _render_peaks_table(peaks: List[Dict[str, float]]) -> str:
    """Render peaks table."""
    if not peaks:
        return "<p>No peaks detected.</p>"

    html = """
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Frequency (Hz)</th>
                    <th>Magnitude</th>
                    <th>Coherence</th>
                    <th>Mode</th>
                </tr>
            </thead>
            <tbody>
    """

    for i, peak in enumerate(peaks):
        coh = peak.get('coherence')
        coh_str = f"{coh:.3f}" if coh else "-"

        html += f"""
            <tr>
                <td>{i + 1}</td>
                <td>{peak.get('freq_hz', 0):.1f}</td>
                <td>{peak.get('magnitude', 0):.4f}</td>
                <td>{coh_str}</td>
                <td>{peak.get('mode', '-')}</td>
            </tr>
        """

    html += "</tbody></table>"
    return html


def _render_wood_properties(props: Dict[str, Any]) -> str:
    """Render wood properties section."""
    grade = props.get("quality_grade", "?")
    grade_class = f"grade-{grade.lower()}"

    return f"""
        <section class="wood-properties">
            <h2>Estimated Wood Properties</h2>
            <div class="info-grid">
                <div class="info-item">
                    <label>Density</label>
                    <span>{props.get('density_kg_m3', '-')} kg/m³</span>
                </div>
                <div class="info-item">
                    <label>Stiffness (E)</label>
                    <span>{props.get('stiffness_along_gpa', '-')} GPa</span>
                </div>
                <div class="info-item">
                    <label>Radiation Coefficient</label>
                    <span>{props.get('radiation_coefficient', '-')}</span>
                </div>
                <div class="info-item">
                    <label>Fundamental</label>
                    <span>{props.get('fundamental_hz', '-')} Hz</span>
                </div>
                <div class="info-item">
                    <label>Damping Factor</label>
                    <span>{props.get('damping_factor', '-') or '-'}</span>
                </div>
                <div class="info-item">
                    <label>Quality Grade</label>
                    <span class="grade {grade_class}">{grade}</span>
                </div>
                <div class="info-item">
                    <label>Confidence</label>
                    <span>{props.get('confidence', 0) * 100:.0f}%</span>
                </div>
            </div>
        </section>
    """


def _generate_spectrum_chart_base64(spectrum_data: Dict[str, Any]) -> str:
    """Generate spectrum chart and return as base64."""
    fig = Figure(figsize=(10, 4), dpi=100)
    fig.patch.set_facecolor('#252526')
    ax = fig.add_subplot(111)
    ax.set_facecolor('#1e1e1e')

    freq = np.array(spectrum_data.get("freq_hz", []))
    mag = np.array(spectrum_data.get("H_mag", []))

    if len(freq) > 0 and len(mag) > 0:
        ax.semilogy(freq, mag, color='#007acc', linewidth=0.8)
        ax.set_xlabel("Frequency (Hz)", color='#cccccc')
        ax.set_ylabel("Magnitude", color='#cccccc')
        ax.set_title("Transfer Function", color='#cccccc')
        ax.tick_params(colors='#cccccc')
        ax.grid(True, alpha=0.3, color='#3d3d3d')
        for spine in ax.spines.values():
            spine.set_color('#3d3d3d')

    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format='png', facecolor='#252526', edgecolor='none')
    buf.seek(0)
    plt.close(fig)

    return base64.b64encode(buf.read()).decode('utf-8')


def _generate_coherence_chart_base64(spectrum_data: Dict[str, Any]) -> str:
    """Generate coherence chart and return as base64."""
    fig = Figure(figsize=(10, 3), dpi=100)
    fig.patch.set_facecolor('#252526')
    ax = fig.add_subplot(111)
    ax.set_facecolor('#1e1e1e')

    freq = np.array(spectrum_data.get("freq_hz", []))
    coh = np.array(spectrum_data.get("coherence", []))

    if len(freq) > 0 and len(coh) > 0:
        ax.plot(freq, coh, color='#4ec9b0', linewidth=0.8)
        ax.axhline(y=0.9, color='#ce9178', linestyle='--', alpha=0.7, label='0.9 threshold')
        ax.set_ylim(0, 1.1)
        ax.set_xlabel("Frequency (Hz)", color='#cccccc')
        ax.set_ylabel("Coherence", color='#cccccc')
        ax.set_title("Measurement Coherence", color='#cccccc')
        ax.tick_params(colors='#cccccc')
        ax.grid(True, alpha=0.3, color='#3d3d3d')
        ax.legend(loc='lower right')
        for spine in ax.spines.values():
            spine.set_color('#3d3d3d')

    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format='png', facecolor='#252526', edgecolor='none')
    buf.seek(0)
    plt.close(fig)

    return base64.b64encode(buf.read()).decode('utf-8')
